sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- sudo curl --fail -L https://github.com/hypriot/rpi-alpine-qemu/raw/master/qemu-arm-static -o /usr/bin/qemu-arm-static
- sudo chmod +x /usr/bin/qemu-arm-static
- sudo curl --fail -L https://github.com/hypriot/rpi-alpine-qemu/raw/master/qemu-arm -o /usr/share/binfmts/qemu-arm
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t hypriot/rpi-mysql .
# test image
- docker run hypriot/rpi-mysql mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hypriot/rpi-mysql hypriot/rpi-mysql:$TAG
    docker push hypriot/rpi-mysql:$TAG
    docker push hypriot/rpi-mysql
  fi
